---

- name: Does our repo already exist locally?
  stat:
    path: "{{ git_checkout_location }}/.git"
  register: git_remote_repo_stat

- name: Clone repo
  git:
    repo: "{{ git_remote_repo_path }}"
    dest: "{{ git_checkout_location }}"

